In [1]:
import pandas as pd
import numpy as np
from pandas.api.types import is_numeric_dtype

In [2]:
#read the file from local
df0=pd.read_csv('/Users/mohammadkhan/Desktop/Data Quality Engineer Data File - BL-Flickr-Images-Book.csv',encoding='utf-8')

In [3]:
#Check for the existing column names
df0.columns

Index(['Identifier', 'Edition Statement', 'Place of Publication',
       'Date of Publication', 'Publisher', 'Title', 'Author', 'Contributors',
       'Corporate Author', 'Corporate Contributors', 'Former owner',
       'Engraver', 'Issuance type', 'Flickr URL', 'Shelfmarks'],
      dtype='object')

In [4]:
#Drop the columns as mentioned in the readme doc
df0.drop(['Edition Statement','Corporate Author','Corporate Contributors',
'Former owner','Engraver','Contributors','Issuance type','Shelfmarks'], axis=1, inplace=True)

In [7]:
#Setting the Index for the df0 as per readme doc
df0.set_index('Identifier', inplace=True)

In [8]:
#Check if the Index is Unique
df0.index.is_unique

True

### Label based Indexing (loc[ ])  vs  Position based Indexing (iloc[ ]) for pandas dataframes

#### Selecting column by label

In [9]:
df0.loc[:,'Publisher'].tail(10)

Identifier
4117751          John Wiley & Sons
4117752             Trübner & Co.
4156359        G. P. Putnam's Sons
4157746     F. C. and J. Rivington
4157862                 T. Fordyce
4158088                        NaN
4158128            M. Mozley & Son
4159563    T. Cadell and W. Davies
4159587           Mackenzie & Dent
4160339                        NaN
Name: Publisher, dtype: object

#### Selecting Column by Index (Position)

In [10]:
df0.iloc[:,2].tail(10)

Identifier
4117751          John Wiley & Sons
4117752             Trübner & Co.
4156359        G. P. Putnam's Sons
4157746     F. C. and J. Rivington
4157862                 T. Fordyce
4158088                        NaN
4158128            M. Mozley & Son
4159563    T. Cadell and W. Davies
4159587           Mackenzie & Dent
4160339                        NaN
Name: Publisher, dtype: object

#### Selecting row by label

In [11]:
df0.loc[667]

Place of Publication                  pp. 40. G. Bryan & Co: Oxford, 1898
Date of Publication                                                   NaN
Publisher                                                             NaN
Title                   The Coming of Spring, and other poems. By J. A...
Author                                                      A., J.|A., J.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 667, dtype: object

#### Selecting row by lndex (Position)

In [ ]:
df0.iloc[7]

#### Selecting rows based on label slices

In [ ]:
df0.loc[[874,2956,3131],'Place of Publication':'Publisher']

#### Selecting rows based on lndex slices

In [ ]:
df0.iloc[[8,16,19],0:3]

In [12]:
# Checking for null values in Date of Publication Column
df0['Date of Publication'].isnull().sum()

181

In [27]:
#Checking for Null Values in Date of Publication Column
df0[df0['Date of Publication'].isnull()]

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
667,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.",http://www.flickr.com/photos/britishlibrary/ta...
11852,"pp. 40. W. Cann: Plymouth, [1876?]",NaN,NaN,"A Question of Holy Writ, suggested by a lectur...","ACKLAND - Lieut., R.N",http://www.flickr.com/photos/britishlibrary/ta...
55031,"pp. vi. 216. Hatchards: London, 1888",NaN,NaN,The White Man's Foot ... With ... illustration...,"Allen, Grant",http://www.flickr.com/photos/britishlibrary/ta...
124885,"pp. 64. W. Cann: Plymouth, [1870?]",NaN,NaN,The Divine Artisan ... A poem. [By Joseph Plim...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
156798,"pp. 95. Erskine Macdonald: London, 1921",NaN,NaN,Reflections. [Verses.] By A. M. B. [i.e. A. M....,"B., A. M.",http://www.flickr.com/photos/britishlibrary/ta...
157633,"pp. xi. 59. J. Parker & Co.: Oxford, [1900.]",NaN,NaN,"The Battle of Maldon, and other renderings fro...","B., F. W. L.",http://www.flickr.com/photos/britishlibrary/ta...
259933,"pp. xii. 59. Thomas Burleigh: London, 1900",NaN,NaN,"The Taking of the Flag, and other recitations,...","BELL, Henry Thomas Mackenzie.",http://www.flickr.com/photos/britishlibrary/ta...
284576,"Москва, 1857-60",NaN,NaN,"Дневникъ Каммеръ-Юнкера Берхгольца, веденный и...","Bergholz, Friedrich Wilhelm von",http://www.flickr.com/photos/britishlibrary/ta...
355309,"pp. 92. Heath Cranton: London, 1919",NaN,NaN,"The City of Renown, and other poems. By C. and...","BIRCH, afterwards SALWEY, Charlotte Maria.",http://www.flickr.com/photos/britishlibrary/ta...
367760,"pp. x. 429. John Murray: London, 1894",NaN,NaN,"Songs, Poems, & Verses. By Helen, Lady Dufferi...","BLACKWOOD, Helen Selina - Baroness Dufferin, a...",http://www.flickr.com/photos/britishlibrary/ta...
381198,"2 vol. W. Blackwood & Sons: Edinburgh, 1888",NaN,NaN,Lady Bluebeard. By the author of 'Zit and Xoe'...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
529537,"pp. 31. S. Harper & Sons: Barnstaple, 1899",NaN,NaN,A Bundle of Sonnets. Based on the Italian mode...,"BUNDLE, Jacob - pseud",http://www.flickr.com/photos/britishlibrary/ta...
727848,"pp. 281. Hatchards: London, [1889.]",NaN,NaN,Under a Cloud. By the author of “The Atelier d...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
804446,"pp. 128. R. Aickin & Co.: Belfast, 1896",NaN,NaN,"Sung by Six. [Poems by] S. K. Cowan, J. H. Cou...","COWAN, Samuel Kennedy.",http://www.flickr.com/photos/britishlibrary/ta...
811126,"pp. 64. W. & J. Kennedy: Hawick, 1899",NaN,NaN,In Borderland. Border and other verses ... Wit...,"CRAIG, Matthew Robert Smith.",http://www.flickr.com/photos/britishlibrary/ta...
848161,"pp. 359. Thomas Nelson & Sons: London, 1889 [1...",NaN,NaN,Pincherton Farm. The story of Maurice Hamilton...,E. A. B. D. (E. A. Bland),http://www.flickr.com/photos/britishlibrary/ta...
856091,"pp. 349. Griffith, Farran, Okeden & Welsh: Lon...",NaN,NaN,"[The White Elephant; or, the Hunters of Ava an...","DALTON, William - Writer of Stories for Children",http://www.flickr.com/photos/britishlibrary/ta...
907096,"pp. 59. Blackwell: Oxford, [1919.]",NaN,NaN,Zoar. A book of verse by Helen & Bernard Bosan...,"DENDY, afterwards BOSANQUET, Helen.",http://www.flickr.com/photos/britishlibrary/ta...
911866,"pp. 110. John Lane: London, New York, 1918",NaN,NaN,[There is no Death. Poems ... With a foreword ...,"DENNYS, Richard Molesworth.",http://www.flickr.com/photos/britishlibrary/ta...
930213,"pp. 221. George Routledge & Sons: London, 1887",NaN,NaN,David & Bathsheba. A royal romance based on ra...,"DICK, Conzae - and CRESWELL (James)",http://www.flickr.com/photos/britishlibrary/ta...
954240,"pp. 152. Москва, 1898",NaN,NaN,Пугачевщина въ Сибири. Очеркъ по документамъ э...,"DMITRIEV-MAMONOV, Aleksandr Ippolitovich - Count",http://www.flickr.com/photos/britishlibrary/ta...
959759,"2 Thle. Frankfurt am Main, 1880, 8º",NaN,NaN,"Lehrbuch der Geschichte der alten Welt, mit be...","DOERING, Emylie.",http://www.flickr.com/photos/britishlibrary/ta...
979058,"Санктпетербургъ, 1867",NaN,NaN,"Очерки Авсрто-Прусской войны въ 1866 году, съ ...","DRAGOMIROV, Mikhail Ivanovich.|DRAGOMIROV, Mik...",http://www.flickr.com/photos/britishlibrary/ta...
980873,"pp. vi. 250. W. Blackwood: Edinburgh, 1889",NaN,NaN,A Dreamer of Dreams. A modern romance. By the ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
994020,pp. 332. Hurst & Blackett: London; Bolton [pri...,NaN,NaN,The Duchess. A story. By the author of “Molly ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
1024863,"pp. vi. 344. Chapman & Hall: London, 1887",NaN,NaN,"I. D. B. (Illicit Diamond Buying), or the Adve...","E., W. T.",http://www.flickr.com/photos/britishlibrary/ta...
1179671,"2 vol. Chatto & Windus: London, 1888",NaN,NaN,"Eve. A novel. By the author of “John Herring,”...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
1197533,"pp. 20. [Appledore Press: New-Haven, Conn.,] 1875",NaN,NaN,Famine: a masque. [By William James Linton.],NaN,http://www.flickr.com/photos/britishlibrary/ta...
1229458,"pp. 229. G. N. Morang & Company: Toronto, 1900",NaN,NaN,Lullaby-Land. Songs of Childhood ... Selected ...,"FIELD, Eugene.",http://www.flickr.com/photos/britishlibrary/ta...
1246734,"Санктпетербургъ, 1845",NaN,NaN,Записки Дюка Лирійскаго и Бервикскаго во время...,"FITZ-JAMES, James Francis - Duke of Berwick an...",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...
3619288,"pp. xii. 139. F. Rodda: Penzance, 1895",NaN,NaN,Randigal Rhymes and a glossary of Cornish Word...,"THOMAS, Joseph - of St. Michael's Mount",http://www.flickr.com/photos/britishlibrary/ta...
3626183,"pp. xx. 372. William P. Nimmo: Edinburgh, 1868",NaN,NaN,"[The Poetical Works of James Thomson, James Be...","Thomson, James",http://www.flickr.com/photos/britishlibrary/ta...
3631247,"pp. vi. 209. Blackwood and Sons: Edinburgh, 1888",NaN,NaN,Thoth. A romance. [By J. S. Nicholson.],NaN,http://www.flickr.com/photos/britishlibrary/ta...
3631248,pp. x. 228. W. Blackwood & Sons: Edinburgh and...,NaN,NaN,[Thoth. A romance. [By J. S. Nicholson.]],NaN,http://www.flickr.com/photos/britishlibrary/ta...
3641137,"pp. 60. Privately printed, 1876",NaN,NaN,Floating Spars. [Verses. With a memoir of the ...,"TINDALE, Thomas Plumpton.",http://www.flickr.com/photos/britishlibrary/ta...
3691484,"pp. 14. W. Cann: Plymouth, [1876?]",NaN,NaN,The Turkish Atrocities. [In verse. By Joseph P...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
3705638,"pp. x. 283. Methuen & Co.: London, 1900",NaN,NaN,The Rubaiyat of Omar Khayyam. Translated by E....,NaN,http://www.flickr.com/photos/britishlibrary/ta...
3705707,"George G. Harrap & Co.: London, [1913.]",NaN,NaN,Rubáiyát of Omar Khayyám. Presented by Will...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
3761232,"pp. xi. 273. Вятка, 1870",NaN,NaN,Исторія Вятскаго края съ древнихъ временъ до н...,"VASIL'EV, S. - of Vyatka and BEKHTEREV (Nikola...",http://www.flickr.com/photos/britishlibrary/ta...
3763128,1885?],NaN,NaN,"The Marquise de Vaudreuil. [A play, by Jemima ...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
3775658,"2 vol. F. V. White & Co.: London, 1888",NaN,NaN,The Honble Mrs. Vereker.-A novel. By the autho...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
3779191,"pp. 87. William Heinemann: London, 1917",NaN,NaN,"War Poems, and other verses ... With an introd...","VERNÈDE, Robert Ernest.",http://www.flickr.com/photos/britishlibrary/ta...
3806535,"pp. 59. Atlas Press: Melbourne, [1900?]",NaN,NaN,The King's Folly and the Queen's Revenge. The ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
3813751,"Санктпетербургъ, 1873",NaN,NaN,Генералъ Фрейтагъ и его боевые товарищы. Три э...,"VOLOTSKOI, Aleksandr A.",http://www.flickr.com/photos/britishlibrary/ta...
3865542,"pp. 50. John Lane: London, 1896",NaN,NaN,The Purple East. A series of sonnets on Englan...,"WATSON, William - Sir, Poet",http://www.flickr.com/photos/britishlibrary/ta...
3893909,"pp. ii. 80. A. W. Dawson: Newport, 1898",NaN,NaN,"West Ward Rhymes, and other verses. By “The Me...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
3926780,"Leeds: Bean & Son; Leamington: Hamblen, 1883",NaN,NaN,[A solitary evening reverie at home. In memori...,"WILKINSON, Edward - Rector of Snargate",http://www.flickr.com/photos/britishlibrary/ta...
3952291,"pp. 77. E. Mathews: London, 1897",NaN,NaN,Lays and Legends of the Weald of Kent ... With...,"WINSER, Lilian.",http://www.flickr.com/photos/britishlibrary/ta...
3993182,"ff. 29. M. Ward & Co.: London and Belfast, 1895",NaN,NaN,"Senilia 1891-1894. [Poems, chiefly in Latin.] ...","Y., W. S.",http://www.flickr.com/photos/britishlibrary/ta...
3995356,"pp. 215. въ Москвѣ, 1889",NaN,NaN,"Сочиненія Князя Курбскаго, какъ историческій м...","YASINSKY, Anton Nikitich.",http://www.flickr.com/photos/britishlibrary/ta...
4018987,"Москва, 1860",NaN,NaN,Подлинныя бумаги до бунта Пугачова относящіяся...,"ZHELEZNOV, Ioasaf Ignat'evich.",http://www.flickr.com/photos/britishlibrary/ta...
4024911,"3 vol. Chapman & Hall: London, 1864",NaN,NaN,Zoe's 'Brand.' By the author of “Recommended t...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4046468,"London: Elliot Stock, 1897",NaN,NaN,Hugo of Avendon. In four acts. By E. L. M. [i....,"DAY, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
4053464,"London: E. Nutt; E. Cooke, 1733",NaN,NaN,A friendly epistle [by Joseph Mitchell?] to th...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4072044,"London: D. Wilson & T. Durham, 1752",NaN,NaN,"The scale: or, Woman weighed with man. A poem ...","MONCREIFF, John.",http://www.flickr.com/photos/britishlibrary/ta...
4077038,"London: printed for Nicholas Vavasour, 1634",NaN,NaN,"The noble souldier. Or, A contract broken, jus...","ROWLEY, Samuel - Dramatist",http://www.flickr.com/photos/britishlibrary/ta...
4112297,"London: Macmillan & Co., pp. xl, 400. 1895",NaN,NaN,Japhet in search of a Father ... With an intro...,"Marryat, Frederick",http://www.flickr.com/photos/britishlibrary/ta...
4113816,"pp. xxvi, 375. London: Jackson, Walford & Hodd...",NaN,NaN,The lacemakers: sketches of Irish characters w...,"MEREDITH, Susanna.|WIBERG, Carl Fredrik.",http://www.flickr.com/photos/britishlibrary/ta...
4114334,"pp. viii. 64. J. Debrett: London, 1789",NaN,NaN,"The Sword of Peace; or, a voyage of love; a co...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4115138,"G. Eld: London, 1608",NaN,NaN,The Revenger's Tagaedie. As it hath beene sund...,NaN,http://www.flickr.com/photos/britishlibrary/ta...

In [13]:
#Creating temporary dataframes for data cleaning of Date of Publication Column
df1=df0.copy()
df2=df0.copy()

The regex:

(?<!\d) - specifies that anything before a set of 4 digits is something that is not a digit;
(\d{4}) - matches 4 digits;
(?!\d) - specifies that anything after a set of 4 digits is something that is not a digit

In [14]:
#Extracts Date of Publication from Place of Publication Column using regex
df1['Date of Publication']=df0.where(df1['Date of Publication'].isnull(),df1['Place of Publication'].str.extract(r'(?<!\d)(\d{4})(?!\d)'),axis=0)

In [15]:
#All but 2 null values are filled with correct data from Place of Publication column
df2['Date of Publication']=df1.where(df2['Date of Publication'].isnull(),df2['Date of Publication'],axis=0)

In [16]:
#Removes any extra characters taking into account only the first date in case of multiple dates 
df2['Date of Publication']=df2['Date of Publication'].str.extract(r'(?<!\d)(\d{4})(?!\d)')

In [18]:
#Checking for numeric data type
is_numeric_dtype(df2['Date of Publication'])

False

In [19]:
# Enforcing the Date of Publication field to Numeric value
df2['Date of Publication'] = pd.to_numeric(df2['Date of Publication'])

In [20]:
#Rechecking the data type of Date of Publication column
is_numeric_dtype(df2['Date of Publication'])

True

In [21]:
#Again checking for null values if any
df2['Date of Publication'].isnull().sum()

2

In [24]:
#Tuple has no date of publication, hence it has NaN as value in df2
df0[df0.index==516336]

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
516336,London,112. G. & W. B. Whittaker,pp. xxvi,"The Italians; or, the Fatal Accusation: a trag...","BUCKE, Charles.",http://www.flickr.com/photos/britishlibrary/ta...

In [25]:
#Tuple has no date of publication, hence it has NaN as value in df2
df0[df0.index==3605102]

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
3605102,Oxford,17 vols. University Press,NaN,The Oxford Thackeray. With illustrations. [Edi...,"Thackeray, William Makepeace",http://www.flickr.com/photos/britishlibrary/ta...

In [28]:
#Creating Temporary Dataframe for Standardizing the Place of Publication Column
df3=df2.copy()

In [29]:
#Filtering out relevant cities from the Place of Publication Column and extracting City names accidently in the publisher column
Plymouth = df3['Place of Publication'].str.contains('Plymouth')
new_haven = df3['Place of Publication'].str.contains('New-Haven')
london = df3['Place of Publication'].str.contains(': London')
edinburg_london = df3['Place of Publication'].str.contains(': Edinburgh and London')
edinburg=df3['Place of Publication'].str.contains(': Edinburgh')
london1= df3['Place of Publication'].str.contains('London:')
oxford=df3['Place of Publication'].str.contains(': Oxford')
hawick=df3['Place of Publication'].str.contains(': Hawick')
barnstaple=df3['Place of Publication'].str.contains(': Barnstaple')
belfast=df3['Place of Publication'].str.contains(': Belfast')
manchester=df3['Place of Publication'].str.contains(': Manchester')
toronto=df3['Place of Publication'].str.contains('Toronto')
dublin=df3['Place of Publication'].str.contains(': Dublin')
newyork=df3['Place of Publication'].str.contains(': New York')
oldham=df3['Place of Publication'].str.contains(': Oldham')
Санктпетербургъ=df3['Place of Publication'].str.contains('Санктпетербургъ')
glasglow=df3['Place of Publication'].str.contains(': Glasgow')
paisley=df3['Place of Publication'].str.contains(': Paisley')
bodmin=df3['Place of Publication'].str.contains(': Bodmin')
hammersmith=df3['Place of Publication'].str.contains(': Hammersmith')
penzance=df3['Place of Publication'].str.contains(': Penzance')
melbourne=df3['Place of Publication'].str.contains(': Melbourne')
newport=df3['Place of Publication'].str.contains(': Newport')
leeds=df3['Place of Publication'].str.contains(': Hamblen')
copenhague=df3['Place of Publication'].str.contains('Copenhague')
montreal=df3['Place of Publication'].str.contains('Montreal')
df3['Place of Publication']=df3['Place of Publication'].str.replace('N.Y','New York')
df3['Place of Publication']=df3['Place of Publication'].str.replace('Phila\\.','Philadelphia')
df3['Place of Publication']=df3['Place of Publication'].str.replace('Saint Lo','St. Louis',regex=True)
df3['Place of Publication']=df3['Place of Publication'].str.replace('Newcastle on Tyne','Newcastle upon Tyne',regex=True)
df3['Place of Publication']=df3['Place of Publication'].str.replace('Newark, N.J','Newark')
df3['Place of Publication']=df3['Place of Publication'].str.replace('Philadelphia, Pa','Philadelphia')
df3['Place of Publication'] = df3['Place of Publication'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
df3['Place of Publication'] = df3['Place of Publication'].replace({'Orleans':'New Orleans','Boston [Mass.]':'Boston'},regex=True)
st_louis=df3['Place of Publication'].str.contains('St. Louis')
albany=df3['Place of Publication'].str.contains('Albany, New York')
auburn=df3['Place of Publication'].str.contains('Auburn, New York')
richmond=df3['Place of Publication'].str.contains('Richmond')
ny_london=df3['Place of Publication'].str.contains('Macmillan & Co')
ednbrg1=df3['Place of Publication'].str.contains('William Nimmo')
ednbrg2=df3['Place of Publication'].str.contains('William Paterson')
ednbrg3=df3['Place of Publication'].str.contains('W P Nimmo')
ednbrg_london=df3['Place of Publication'].str.contains('William Blackwood & Sons')
london11=df3['Place of Publication'].str.contains('Willoughby ')
london22=df3['Place of Publication'].str.contains('Ward & Lock')
london33=df3['Place of Publication'].str.contains('W H Allen & Co')
london44=df3['Place of Publication'].str.contains('Vernor, Hood, & Sharpe, etc')
london55=df3['Place of Publication'].str.contains('Service & Paton')
london66=df3['Place of Publication'].str.contains('sold by J. Newbery; M. Cooper')
london77=df3['Place of Publication'].str.contains('Smith, Elder & Co')
london88=df3['Place of Publication'].str.contains('Richard Bentley & Son')
london99=df3['Place of Publication'].str.contains('Remington & Co')
london111=df3['Place of Publication'].str.contains('Parker Son and Bourne')
london222=df3['Place of Publication'].str.contains('M Cooper')
london333=df3['Place of Publication'].str.contains('John ')
london444=df3['Place of Publication'].str.contains('James ')
london555=df3['Place of Publication'].str.contains('J. ')
london666=df3['Place of Publication'].str.contains('Henry G Bohn')
london777=df3['Place of Publication'].str.contains('Harrison')
london888=df3['Place of Publication'].str.contains('George Routledge & Sons')
london999=df3['Place of Publication'].str.contains('G. ')
london1111=df3['Place of Publication'].str.contains('Francis & John Rivington')
london2222=df3['Place of Publication'].str.contains('Cassell')
london3333=df3['Place of Publication'].str.contains('Bradbury & Evans')
london4444=df3['Place of Publication'].str.contains('Bliss')
london5555=df3['Place of Publication'].str.contains('Bernard Lintot')
london6666=df3['Place of Publication'].str.contains('B Law')
london7777=df3['Place of Publication'].str.contains('Bell & Daldy')
london8888=df3['Place of Publication'].str.contains('A Strahan')
london9999=df3['Place of Publication'].str.contains('A Millar')
lndn1=df3['Place of Publication'].str.contains('Bickers & Son')
madras=df3['Place of Publication'].str.contains('V Kalyanaram')
ny_b=df3['Place of Publication'].str.contains('Morse Co')
ny_l1=df3['Place of Publication'].str.contains('Macmillan & Co')
ny_l2=df3['Place of Publication'].str.contains('Alexander Strahan')
b_l=df3['Place of Publication'].str.contains('Ginn & Co')
cmb_l=df3['Place of Publication'].str.contains('Jones & Piggott')
ny_p1=df3['Place of Publication'].str.contains('Home Publishing Co')
ny_p2=df3['Place of Publication'].str.contains('Harper & Bros')
ny_p3=df3['Place of Publication'].str.contains('D. Appleton & Co')
bs1=df3['Place of Publication'].str.contains('D. C. Heath & Co')
calcutta=df3['Place of Publication'].str.contains('Baptist Mission Press')
frankfurt=df3['Place of Publication'].str.contains('Frank')
exeter=df3['Place of Publication'].str.contains('Exeter')
providence=df3['Place of Publication'].str.contains('Providence')
jamaica=df3['Place of Publication'].str.contains('Jamaica')
konigsberg=df3['Place of Publication'].str.contains('Konigsberg')
springfield=df3['Place of Publication'].str.contains('Springfield')
st_pts=df3['Place of Publication'].str.contains('St. Petersbourg')

In [31]:
#
df3['Place of Publication'] = np.where(Plymouth,'Plymouth',np.where(new_haven,'New Haven',np.where(edinburg_london,'Edinburgh and London',
np.where(edinburg,'Edinburgh',np.where(london, 'London',np.where(london1,'London',np.where(oxford,'Oxford',np.where(hawick,'Hawick',np.where(barnstaple,'Barnstaple',
np.where(belfast,'Belfast',np.where(manchester,'Manchester',np.where(toronto,'Toronto',np.where(dublin,'Dublin',np.where(newyork,'New York',
np.where(oldham,'oldham',np.where(Санктпетербургъ,'Санктпетербургъ',np.where(glasglow,'Glasglow',np.where(paisley,'Paisley',np.where(bodmin,'Bodmin',
np.where(hammersmith,'Hammersmith',np.where(penzance,'Penzance',np.where(melbourne,'Melbourne',np.where(newport,'Newport',
np.where(leeds,'Leeds',np.where(copenhague,'Copenhagen',np.where(montreal,'Montreal',np.where(st_louis,'St. Louis',np.where(albany,'Albany',
np.where(auburn,'Auburn',np.where(richmond,'Richmond',np.where(ny_london,'London and New York',np.where(ednbrg1,'Edinburgh',
np.where(ednbrg2,'Edinburgh',np.where(ednbrg3,'Edinburgh',np.where(ednbrg_london,'Edinburgh and London',np.where(london11,'London',np.where(london22,'London',
np.where(london33,'London',np.where(london44,'London',np.where(london55,'London',np.where(london66,'London',np.where(london77,'London',np.where(london88,'London',
np.where(london99,'London',np.where(london111,'London',np.where(london222,'London',np.where(london333,'London',np.where(london444,'London',np.where(london555,'London',
np.where(london666,'London',np.where(london777,'London',np.where(london888,'London',np.where(london999,'London',np.where(london1111,'London',np.where(london2222,'London',
np.where(london3333,'London',np.where(london4444,'London',np.where(london5555,'London',np.where(london6666,'London',np.where(london7777,'London',np.where(london8888,'London',
np.where(london9999,'London',np.where(ny_b,'New York and Boston',np.where(ny_l1,'New York and London',np.where(ny_l2,'New York and London',np.where(cmb_l,'Cambridge and London',
np.where(ny_p1,'New York',np.where(ny_p2,'New York',np.where(ny_p3,'New York',np.where(b_l,'Boston and London',np.where(bs1,'Boston',np.where(madras,'Madras',
np.where(calcutta,'Calcutta', np.where(lndn1,'London',np.where(frankfurt,'Frankfurt',np.where(exeter,'Exeter',np.where(providence,'Providence',np.where(jamaica,'Jamaica',
np.where(konigsberg,'Konigsberg',np.where(springfield,'Springfield',np.where(st_pts,'St. Petersburg', df3['Place of Publication'].str.replace('-', ' ')))))))))))))))))))))))))))
)))))))))))))))))))))))))))))))))))))))))))))))))))))))

In [32]:
#Using Regex to get rid of extra charachters
pattern = '|'.join(['\\[printed]', 'printed', 'reprinted','\\[U.S.]','U.S.*','Mass.*','\\[Minn.]','\\[Conn.]','\d+','\'s','\\[sic]','\\?','\\[','\\]',', Ill','pp.','; Virtue & Yorston','\\(','Printed for private circulation','Private Impression: ',
'Published in  pts','W. Frederick',' F. P. Harper',' Phillipson & Golder',' Cole Book Arcade','E. P. Dutton & Co','Aylesbury','Scribner, Welford, & Armstrong','T. Merrill','Longman & Co.','series','For Charles Harper.','pp. . D. Nutt; In the Strand','T. C. Newby','^v.','etc.: Thomas Nelson & Sons','xxxi','Privately','by B Dewhirst'])

df3['Place of Publication'] = df3['Place of Publication'].str.replace(pattern,'')

In [37]:
#Restructuring the data after cleaning 
df3['Place of Publication']=df3['Place of Publication'].replace('\;',',', regex=True).replace('\.','', regex=True).replace('\&',',', regex=True).replace('and',',', regex=True).replace('\:','', regex=True)

In [39]:
#Whitespaces cleanup
df3['Place of Publication']=df3['Place of Publication'].str.strip()

In [40]:
df3.to_csv('/Users/mohammadkhan/Desktop/flickr_data/std_final_df.csv')

In [45]:
#Deleting all the temporary dataframes 
del df1
del df2

In [47]:
del df3